# Generated by Django 3.0.5 on 2020-04-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='imge',
            new_name='iamge',
        ),
        migrations.AlterField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(),
        ),
    ]
