# Generated by Django 3.0.5 on 2020-04-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20200408_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='iamge',
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='offer',
            field=models.IntegerField(),
        ),
    ]
